# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"\x07\n\x05\x45mpty\",\n\x04Term\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x1e\n\x0bTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\")\n\x08TermList\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term\"3\n\x0fOperationStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa4\x02\n\x0fGlossaryService\x12\x30\n\tListTerms\x12\x0f.glossary.Empty\x1a\x12.glossary.TermList\x12\x30\n\x07GetTerm\x12\x15.glossary.TermRequest\x1a\x0e.glossary.Term\x12\x34\n\x07\x41\x64\x64Term\x12\x0e.glossary.Term\x1a\x19.glossary.OperationStatus\x12\x37\n\nUpdateTerm\x12\x0e.glossary.Term\x1a\x19.glossary.OperationStatus\x12>\n\nDeleteTerm\x12\x15.glossary.TermRequest\x1a\x19.glossary.OperationStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_TERM']._serialized_start=37
  _globals['_TERM']._serialized_end=81
  _globals['_TERMREQUEST']._serialized_start=83
  _globals['_TERMREQUEST']._serialized_end=113
  _globals['_TERMLIST']._serialized_start=115
  _globals['_TERMLIST']._serialized_end=156
  _globals['_OPERATIONSTATUS']._serialized_start=158
  _globals['_OPERATIONSTATUS']._serialized_end=209
  _globals['_GLOSSARYSERVICE']._serialized_start=212
  _globals['_GLOSSARYSERVICE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
